name: Hexo Deploy

on:
  push:
    branches:
      - main   # 如果你是 master 就改成 master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies (force CJS)
        run: |
          npm install
          npm install strip-ansi@6.0.1 --save-exact
          npm install hexo-cli -g

      - name: Hexo clean
        run: ./node_modules/.bin/hexo clean

      - name: Hexo generate
        run: ./node_modules/.bin/hexo generate

      - name: Deploy to GitHub Pages
        run: ./node_modules/.bin/hexo deploy
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
